<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.02" os="Windows 7" host="INPUHJLP06355"><DocLocation><![CDATA[C:\Git_Repo\TM_SQA_OrangeHRM\OrangeHRM_Firefox]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[OrangeHRM_Firefox]]></DName>
<Res><![CDATA[OrangeHRM_Firefox]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="14" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[25/06/2018 - 0:21:47]]></Time>
<TimeTick>1529866307</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "firefox.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "firefox.exe",1]]></Details>
<Time><![CDATA[25/06/2018 - 0:21:47]]></Time>
<TimeTick>1529866307</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="11" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "firefox.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="17" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:21:48]]></Time>
<TimeTick>1529866308</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="19" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:21:50]]></Time>
<TimeTick>1529866310</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="27" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:21:51]]></Time>
<TimeTick>1529866311</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="35" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:21:52]]></Time>
<TimeTick>1529866312</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="43" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:21:53]]></Time>
<TimeTick>1529866313</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="51" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:21:55]]></Time>
<TimeTick>1529866315</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="59" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:21:56]]></Time>
<TimeTick>1529866316</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="67" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:21:57]]></Time>
<TimeTick>1529866317</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="75" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:21:58]]></Time>
<TimeTick>1529866318</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="83" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:00]]></Time>
<TimeTick>1529866320</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="91" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:01]]></Time>
<TimeTick>1529866321</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="99" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:02]]></Time>
<TimeTick>1529866322</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="107" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:04]]></Time>
<TimeTick>1529866324</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="115" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:05]]></Time>
<TimeTick>1529866325</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="123" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:09]]></Time>
<TimeTick>1529866329</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="131" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:10]]></Time>
<TimeTick>1529866330</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="139" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:12]]></Time>
<TimeTick>1529866332</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="147" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:13]]></Time>
<TimeTick>1529866333</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="155" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:14]]></Time>
<TimeTick>1529866334</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="163" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:16]]></Time>
<TimeTick>1529866336</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="171" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:17]]></Time>
<TimeTick>1529866337</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="179" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:19]]></Time>
<TimeTick>1529866339</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="187" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:20]]></Time>
<TimeTick>1529866340</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="195" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:21]]></Time>
<TimeTick>1529866341</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="203" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:24]]></Time>
<TimeTick>1529866344</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="211" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:25]]></Time>
<TimeTick>1529866345</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="219" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ LOGIN ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:27]]></Time>
<TimeTick>1529866347</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="221" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ LOGIN ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ txtUsername ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:28]]></Time>
<TimeTick>1529866348</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="223" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ txtUsername ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ txtUsername ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Admin"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:29]]></Time>
<TimeTick>1529866349</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="226" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ txtUsername ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[Username Set]]></Obj>
<Details ><![CDATA[Successfully Set]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:29]]></Time>
<TimeTick>1529866349</TimeTick>
<NodeArgs eType="User" icon="20" nRep="227" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Username Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ txtPassword ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:29]]></Time>
<TimeTick>1529866349</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="229" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ txtPassword ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ txtPassword ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["5b051c35be3517e6cada111aa95cf7ba"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:30]]></Time>
<TimeTick>1529866350</TimeTick>
<NodeArgs eType="Replay" icon="19" nRep="232" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ txtPassword ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[Password Set]]></Obj>
<Details ><![CDATA[Successfully Set]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:30]]></Time>
<TimeTick>1529866350</TimeTick>
<NodeArgs eType="User" icon="20" nRep="233" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ LOGIN ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:30]]></Time>
<TimeTick>1529866350</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="235" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ LOGIN ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ LOGIN ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:30]]></Time>
<TimeTick>1529866350</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="238" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ LOGIN ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[Login Button Click]]></Obj>
<Details ><![CDATA[Successfully Clicked]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:30]]></Time>
<TimeTick>1529866350</TimeTick>
<NodeArgs eType="User" icon="20" nRep="239" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login Button Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ Welcome Admin ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:34]]></Time>
<TimeTick>1529866354</TimeTick>
<NodeArgs eType="Replay" icon="21" nRep="241" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ Welcome Admin ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ Welcome Admin ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:35]]></Time>
<TimeTick>1529866355</TimeTick>
<NodeArgs eType="Replay" icon="21" nRep="244" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ Welcome Admin ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[Welcome Link Click]]></Obj>
<Details ><![CDATA[Successfully Clicked]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:35]]></Time>
<TimeTick>1529866355</TimeTick>
<NodeArgs eType="User" icon="20" nRep="245" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome Link Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ Logout ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:35]]></Time>
<TimeTick>1529866355</TimeTick>
<NodeArgs eType="Replay" icon="21" nRep="247" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ Logout ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ Logout ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:36]]></Time>
<TimeTick>1529866356</TimeTick>
<NodeArgs eType="Replay" icon="21" nRep="250" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ Logout ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[Logout Link Click]]></Obj>
<Details ><![CDATA[Successfully Clicked]]></Details>
<Time><![CDATA[25/06/2018 - 0:22:36]]></Time>
<TimeTick>1529866356</TimeTick>
<NodeArgs eType="User" icon="20" nRep="251" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Logout Link Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/06/2018 - 0:21:42" eTime="25/06/2018 - 0:22:38" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="16" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="15" nRep="6" status="Passed" >
<Disp><![CDATA[OrangeHRM_Firefox Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="25/06/2018 - 0:21:40" eTime="25/06/2018 - 0:22:38" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="13" nRep="3" status="Passed" >
<Disp><![CDATA[Test OrangeHRM_Firefox Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>