<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.02" os="Windows 7" host="INPUHJLP06355"><DocLocation><![CDATA[C:\Git_Repo\TM_SQA_OrangeHRM\OrangeHRM_IE]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[OrangeHRM_IE]]></DName>
<Res><![CDATA[OrangeHRM_IE]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="13" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:13]]></Time>
<TimeTick>1529866393</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:13]]></Time>
<TimeTick>1529866393</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="11" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="16" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:15]]></Time>
<TimeTick>1529866395</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="19" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:16]]></Time>
<TimeTick>1529866396</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="27" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:17]]></Time>
<TimeTick>1529866397</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="35" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:18]]></Time>
<TimeTick>1529866398</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="43" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:20]]></Time>
<TimeTick>1529866400</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="51" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:21]]></Time>
<TimeTick>1529866401</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="59" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:22]]></Time>
<TimeTick>1529866402</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="67" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:23]]></Time>
<TimeTick>1529866403</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="75" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:25]]></Time>
<TimeTick>1529866405</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="83" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:26]]></Time>
<TimeTick>1529866406</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="91" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:27]]></Time>
<TimeTick>1529866407</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="99" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:29]]></Time>
<TimeTick>1529866409</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="107" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:30]]></Time>
<TimeTick>1529866410</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="115" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:31]]></Time>
<TimeTick>1529866411</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="123" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:32]]></Time>
<TimeTick>1529866412</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="131" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:46]]></Time>
<TimeTick>1529866426</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="134" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ LOGIN ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:47]]></Time>
<TimeTick>1529866427</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="136" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ LOGIN ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ txtUsername ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:47]]></Time>
<TimeTick>1529866427</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="138" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ txtUsername ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ txtUsername ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Admin"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:47]]></Time>
<TimeTick>1529866427</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="141" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ txtUsername ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[Username Set]]></Obj>
<Details ><![CDATA[Successfully Set]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:47]]></Time>
<TimeTick>1529866427</TimeTick>
<NodeArgs eType="User" icon="19" nRep="142" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Username Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ txtPassword ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:47]]></Time>
<TimeTick>1529866427</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="144" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ txtPassword ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ txtPassword ].SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5b068f0c477121820ccbafa7e2a6ee06"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:48]]></Time>
<TimeTick>1529866428</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="147" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ txtPassword ].SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Password Set]]></Obj>
<Details ><![CDATA[Successfully Set]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:48]]></Time>
<TimeTick>1529866428</TimeTick>
<NodeArgs eType="User" icon="19" nRep="148" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ LOGIN ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:48]]></Time>
<TimeTick>1529866428</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="150" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ LOGIN ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ LOGIN ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:48]]></Time>
<TimeTick>1529866428</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="153" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ LOGIN ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA[Login Button Click]]></Obj>
<Details ><![CDATA[Successfully Clicked]]></Details>
<Time><![CDATA[25/06/2018 - 0:23:48]]></Time>
<TimeTick>1529866428</TimeTick>
<NodeArgs eType="User" icon="19" nRep="154" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login Button Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/06/2018 - 0:23:10" eTime="25/06/2018 - 0:23:56" passed="4" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="15" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="14" nRep="6" status="Passed" >
<Disp><![CDATA[OrangeHRM_IE Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="25/06/2018 - 0:23:09" eTime="25/06/2018 - 0:23:56" passed="4" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="12" nRep="3" status="Passed" >
<Disp><![CDATA[Test OrangeHRM_IE Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>